version: '3'
services:
  mysql:
    image: mariadb:10.5.9
    command: --max_allowed_packet=256M
    volumes:
      - "data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    networks:
      oti_x42_com:
        aliases:
          - oti_x42_com
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 5

  litespeed:
    image: litespeedtech/openlitespeed:${OLS_VERSION}-${PHP_VERSION}
    environment:
      TZ: America/New_York
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.oti_x42_com.rule=Host(`oti.x42.com`)"
      - "traefik.http.routers.oti_x42_com.entrypoints=websecure"
      - "traefik.http.services.oti_x42_com.loadbalancer.server.port=80"
      - "traefik.http.routers.oti_x42_com.tls.certresolver=myresolver"
    volumes:
        - lsws_conf:/usr/local/lsws/conf
        - lsws_admin-conf:/usr/local/lsws/admin/conf
        - container:/usr/local/bin
        - sites:/var/www/vhosts/
        - acme:/root/.acme.sh/
        - logs:/usr/local/lsws/logs/
    restart: always
    networks:
      proxy:
        aliases:
          - proxy
      oti_x42_com:
        aliases:
          - oti_x42_com
    depends_on:
            mysql:
                condition: service_healthy
      
networks:
  proxy:
    external: true
    name: proxy
  oti_x42_com:
    external: false
    name: oti_x42_com
volumes:
  lsws_conf:
  lsws_admin-conf:
  container:
  sites:
  acme:
  logs:
  data: